name: Build Kernel for mt7621

on:
  pull_request:
    paths:
      - 'target/linux/ramips/mt7621/**'
  push:
    paths:
      - 'target/linux/ramips/mt7621/**'
    branches-ignore:
      - master
  workflow_dispatch:  # Позволяет запускать workflow вручную

permissions:
  contents: read

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Используем ваш форк

      - name: Set up OpenWRT build environment
        run: |
          # Установите необходимые зависимости
          sudo apt-get update
          sudo apt-get install -y build-essential git libpcre3-dev

      - name: Update OpenWRT feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure Kernel
        run: |
          make kernel_menuconfig  # Настройка только ядра

      - name: Build Kernel for mt7621
        run: |
          make kernel -j$(nproc)  # Сборка только ядра

      - name: Upload built kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: bin/targets/ramips/mt7621/*.bin  # Укажите путь к вашим скомпилированным файлам
