name: Build Kernel for mt7621

on:
  pull_request:
    paths:
      - 'target/linux/ramips/mt7621/**'
  push:
    paths:
      - 'target/linux/ramips/mt7621/**'
    branches-ignore:
      - master
  workflow_dispatch:  # Позволяет запускать workflow вручную

permissions:
  contents: read

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновлено до v4

      - name: Set up OpenWRT build environment
        run: |
          # Установите необходимые зависимости
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Clone OpenWRT repository
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Kernel for mt7621
        run: |
          cd openwrt
          make menuconfig  # Настройка конфигурации, выберите mt7621
          make -j$(nproc)  # Сборка
